---
abstract: 'System V and POSIX timezone strings'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Date::ISO8601: 0
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.006
  strict: 0
  warnings: 0
dynamic_config: 0
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-TimeZone-SystemV
provides:
  DateTime::TimeZone::SystemV:
    file: lib/DateTime/TimeZone/SystemV.pm
    version: 0.008
requires:
  Carp: 0
  Date::ISO8601: 0
  Params::Classify: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.fysh.org/zefram/DateTime-TimeZone-SystemV.git
version: 0.008
