---
abstract: 'System V and POSIX timezone strings'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.006
  strict: 0
  warnings: 0
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-TimeZone-SystemV
provides:
  DateTime::TimeZone::SystemV:
    file: lib/DateTime/TimeZone/SystemV.pm
    version: 0.004
requires:
  Carp: 0
  Date::ISO8601: 0
  Date::JD: 0.002
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.004
